// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Samoloty.Entitiesss;

namespace Samoloty.Entitiesss.Migrations
{
    [DbContext(typeof(SamolotyyyyContext))]
    [Migration("20180811095808_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Samoloty.Entitiesss.Lot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Numer");

                    b.HasKey("ID");

                    b.ToTable("Loty");
                });

            modelBuilder.Entity("Samoloty.Entitiesss.Rezerwacje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID");

                    b.ToTable("Rezerwacjes");
                });

            modelBuilder.Entity("Samoloty.Entitiesss.Samoloty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.HasKey("ID");

                    b.ToTable("Samoloty");
                });
#pragma warning restore 612, 618
        }
    }
}
